name: Deploy-Test-TreasuresCakes-Com
on:
  push:
    branches:    
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Update wp-config DB Name
      uses: jacobtomlinson/gha-find-replace@0.1.1
      with:
        include: wp-config
        find: "define( 'DB_NAME', 'wp_local_db' );"
        replace: "define( 'DB_NAME', 'treasure_cakes_dev' );" 
        
    - name: Update wp-config DB Host and Port
      uses: jacobtomlinson/gha-find-replace@0.1.1
      with:
        include: wp-config
        find: "define( 'DB_HOST', 'localhost:3308' );"
        replace: "define( 'DB_HOST', 'localhost:3306' );" 

    - name: Deploying to test.treasurescakes.com
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.treasurescakes.ca
        FTP_USERNAME: ikstransfer@treasurescakes.ca
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: wordpress
        REMOTE_DIR: /tc-test
        ARGS: --delete --delete-excluded --verbose --exclude-glob=*.iml  --exclude-glob=.idea/** --exclude-glob=.git/** --exclude-glob=.github/**


