name: Dev-Deploy-AccessWebspace
on:
  push:
    branches:    
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Deploying to Yash-Access-Webspace
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: users.accesscomm.ca/
        FTP_USERNAME: yashghatti
        FTP_PASSWORD: ghattinet_1995
        REMOTE_DIR: RevampTreasures
        ARGS: --delete

