name: Dev-Deploy-AccessWebspace
on:
  push:
    branches:    
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Deploying to Yash-Access-Webspace
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.treasurescakes.ca
        FTP_USERNAME: ikstransfer@treasurescakes.ca
        FTP_PASSWORD: cakes_2020
        REMOTE_DIR: /tc-test
        ARGS: --delete --delete-excluded --verbose --exclude=**.iml
